/* eslint-disable operator-linebreak */

// WEB3 CONTEXT
export const SET_WEB3_PROVIDER = 'SET_WEB3_PROVIDER';
export const SET_ADDRESS = 'SET_ADDRESS';
export const RESET_WEB3_PROVIDER = 'RESET_WEB3_PROVIDER';

// MINTING MODAL
export const OPEN_MINTING_MODAL = 'OPEN_MINTING_MODAL';
export const CLOSE_MINTING_MODAL = 'CLOSE_MINTING_MODAL';

// WELCOME MODAL
export const OPEN_WELCOME_MODAL = 'OPEN_WELCOME_MODAL';
export const CLOSE_WELCOME_MODAL = 'CLOSE_WELCOME_MODAL';

// ANIMATION
export const ANIMATION = 'ANIMATION';
